name: update-deps

on:
  schedule:
    - cron: "0 23 * * 5"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Update dependencies
        run: npm run update
      - name: Set current date
        run: echo "MY_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: update dependencies - ${{ env.MY_DATE }}
          branch: update-dependencies
          delete-branch: true
          base: main
          title: update dependencies
          body: update dependencies
          labels: dependencies
          reviewers: spnraju
